### ISSUE TITLE
Should we propose UGRID to CF?

### ISSUE THREAD

**Issue by rsignell-usgs** [ugrid-conventions/ugrid-conventions#13] opened 2015-03-18 11:08 UTC
We've always thought of UGRID is an _extension_ of CF, and we have talked about eventually proposing UGRID to the CF group for formal inclusion.   

Some advantages of becoming part of CF:
- we get vetting and by-in from a larger group
- we could simplify our conventions attribute to  "CF-X.X" and drop the "UGRID". 

But there are disadvantages as well:
- improvements to the UGRID spec would happen much more slowly
- we could not be able to implement non-CF components such as https://github.com/ugrid-conventions/ugrid-conventions/issues/12 without getting them approved for CF as well

What do folks think?

**Comment by pelson** [comment] 2018-05-22 16:11
Dupe of #38?

**Comment by ChrisBarker-NOAA** [comment] 2018-05-23 01:54
Well, yes, though #38 is about actually moving forward. But thanks, we don't need them both.

**Closed by ChrisBarker-NOAA** 2018-05-23 01:54 UTC
